# Application name
spring:
  application:
    name: Study-Hive

  datasource:
    url: jdbc:postgresql://localhost:5432/studyhivedb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Server port
server:
  port: 8090

