spring:
  application:
    name: Study-Hive

  datasource:
    url: jdbc:postgresql://localhost:5432/studyhivedb
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  address: 0.0.0.0
  port: 8090
